import '../models/quran/sura_name_model.dart';
import '../presentation/widgets/custom_category.dart';

var categoriesList = [
  MyCategory(
    categoryTitle: 'Quran',
    imagePath: "assets/images/quran.png",
    onTap: () {},
  ),
  MyCategory(
    categoryTitle: 'Hadith',
    imagePath: "assets/images/masgid1.png",
    onTap: () {},
  ),
  MyCategory(
    categoryTitle: 'Tasbeh',
    imagePath: "assets/images/sbha.png",
    onTap: () {},
  ),
];

List<SuraNameModel> completeSurahList = [
  SuraNameModel(name: "الفاتحة", isMakke: true, numberOfAyat: 7),
  SuraNameModel(name: "البقرة", isMakke: false, numberOfAyat: 286),
  SuraNameModel(name: "آل عمران", isMakke: false, numberOfAyat: 200),
  SuraNameModel(name: "النساء", isMakke: false, numberOfAyat: 176),
  SuraNameModel(name: "المائدة", isMakke: false, numberOfAyat: 120),
  SuraNameModel(name: "الأنعام", isMakke: false, numberOfAyat: 165),
  SuraNameModel(name: "الأعراف", isMakke: false, numberOfAyat: 206),
  SuraNameModel(name: "الأنفال", isMakke: true, numberOfAyat: 75),
  SuraNameModel(name: "التوبة", isMakke: false, numberOfAyat: 129),
  SuraNameModel(name: "يونس", isMakke: true, numberOfAyat: 109),
  SuraNameModel(name: "هود", isMakke: true, numberOfAyat: 123),
  SuraNameModel(name: "يوسف", isMakke: true, numberOfAyat: 111),
  SuraNameModel(name: "الرعد", isMakke: true, numberOfAyat: 39),
  SuraNameModel(name: "إبراهيم", isMakke: true, numberOfAyat: 71),
  SuraNameModel(name: "الحجر", isMakke: true, numberOfAyat: 99),
  SuraNameModel(name: "النحل", isMakke: true, numberOfAyat: 128),
  SuraNameModel(name: "الإسراء", isMakke: true, numberOfAyat: 111),
  SuraNameModel(name: "الكهف", isMakke: true, numberOfAyat: 110),
  SuraNameModel(name: "مريم", isMakke: true, numberOfAyat: 98),
  SuraNameModel(name: "طه", isMakke: true, numberOfAyat: 83),
  SuraNameModel(name: "الأنبياء", isMakke: true, numberOfAyat: 112),
  SuraNameModel(name: "الحج", isMakke: true, numberOfAyat: 78),
  SuraNameModel(name: "المؤمنون", isMakke: true, numberOfAyat: 112),
  SuraNameModel(name: "النور", isMakke: true, numberOfAyat: 64),
  SuraNameModel(name: "الفرقان", isMakke: true, numberOfAyat: 77),
  SuraNameModel(name: "الشعراء", isMakke: true, numberOfAyat: 227),
  SuraNameModel(name: "النمل", isMakke: true, numberOfAyat: 93),
  SuraNameModel(name: "القصص", isMakke: true, numberOfAyat: 85),
  SuraNameModel(name: "العنكبوت", isMakke: true, numberOfAyat: 69),
  SuraNameModel(name: "الروم", isMakke: true, numberOfAyat: 60),
  SuraNameModel(name: "لقمان", isMakke: true, numberOfAyat: 78),
  SuraNameModel(name: "السجدة", isMakke: true, numberOfAyat: 30),
  SuraNameModel(name: "الأحزاب", isMakke: true, numberOfAyat: 73),
  SuraNameModel(name: "سبأ", isMakke: true, numberOfAyat: 54),
  SuraNameModel(name: "فاطر", isMakke: true, numberOfAyat: 46),
  SuraNameModel(name: "يس", isMakke: true, numberOfAyat: 83),
  SuraNameModel(name: "الصافات", isMakke: true, numberOfAyat: 88),
  SuraNameModel(name: "ص", isMakke: true, numberOfAyat: 87),
  SuraNameModel(name: "الزمر", isMakke: true, numberOfAyat: 75),
  SuraNameModel(name: "غافر", isMakke: true, numberOfAyat: 85),
  SuraNameModel(name: "فصلت", isMakke: true, numberOfAyat: 88),
  SuraNameModel(name: "الشورى", isMakke: true, numberOfAyat: 53),
  SuraNameModel(name: "الزخرف", isMakke: true, numberOfAyat: 89),
  SuraNameModel(name: "الدخان", isMakke: true, numberOfAyat: 56),
  SuraNameModel(name: "الجاثية", isMakke: true, numberOfAyat: 37),
  SuraNameModel(name: "الأحقاف", isMakke: true, numberOfAyat: 45),
  SuraNameModel(name: "محمد", isMakke: false, numberOfAyat: 38),
  SuraNameModel(name: "الفتح", isMakke: false, numberOfAyat: 29),
  SuraNameModel(name: "الحجرات", isMakke: false, numberOfAyat: 18),
  SuraNameModel(name: "ق", isMakke: true, numberOfAyat: 45),
  SuraNameModel(name: "الذاريات", isMakke: true, numberOfAyat: 60),
  SuraNameModel(name: "الطور", isMakke: true, numberOfAyat: 49),
  SuraNameModel(name: "النجم", isMakke: true, numberOfAyat: 62),
  SuraNameModel(name: "القمر", isMakke: true, numberOfAyat: 55),
  SuraNameModel(name: "الرحمن", isMakke: true, numberOfAyat: 78),
  SuraNameModel(name: "الواقعة", isMakke: true, numberOfAyat: 96),
  SuraNameModel(name: "الحديد", isMakke: false, numberOfAyat: 29),
  SuraNameModel(name: "المجادلة", isMakke: false, numberOfAyat: 22),
  SuraNameModel(name: "الحشر", isMakke: false, numberOfAyat: 24),
  SuraNameModel(name: "الممتحنة", isMakke: false, numberOfAyat: 13),
  SuraNameModel(name: "الصف", isMakke: false, numberOfAyat: 14),
  SuraNameModel(name: "الجمعة", isMakke: false, numberOfAyat: 12),
  SuraNameModel(name: "المنافقون", isMakke: false, numberOfAyat: 11),
  SuraNameModel(name: "التغابن", isMakke: false, numberOfAyat: 18),
  SuraNameModel(name: "الطلاق", isMakke: false, numberOfAyat: 12),
  SuraNameModel(name: "التحريم", isMakke: false, numberOfAyat: 12),
  SuraNameModel(name: "الملك", isMakke: true, numberOfAyat: 30),
  SuraNameModel(name: "القلم", isMakke: true, numberOfAyat: 52),
  SuraNameModel(name: "الحاقة", isMakke: true, numberOfAyat: 52),
  SuraNameModel(name: "المعارج", isMakke: true, numberOfAyat: 44),
  SuraNameModel(name: "نوح", isMakke: true, numberOfAyat: 28),
  SuraNameModel(name: "الجن", isMakke: true, numberOfAyat: 28),
  SuraNameModel(name: "المزمل", isMakke: true, numberOfAyat: 20),
  SuraNameModel(name: "المدثر", isMakke: true, numberOfAyat: 56),
  SuraNameModel(name: "القيامة", isMakke: true, numberOfAyat: 40),
  SuraNameModel(name: "الإنسان", isMakke: true, numberOfAyat: 33),
  SuraNameModel(name: "المرسلات", isMakke: true, numberOfAyat: 50),
  SuraNameModel(name: "النبأ", isMakke: true, numberOfAyat: 40),
  SuraNameModel(name: "النازعات", isMakke: true, numberOfAyat: 46),
  SuraNameModel(name: "عبس", isMakke: true, numberOfAyat: 42),
  SuraNameModel(name: "التكوير", isMakke: true, numberOfAyat: 29),
  SuraNameModel(name: "الانفطار", isMakke: true, numberOfAyat: 19),
  SuraNameModel(name: "المطففين", isMakke: true, numberOfAyat: 36),
  SuraNameModel(name: "الأنشقاق", isMakke: true, numberOfAyat: 25),
  SuraNameModel(name: "البروج", isMakke: true, numberOfAyat: 22),
  SuraNameModel(name: "الطارق", isMakke: true, numberOfAyat: 17),
  SuraNameModel(name: "الأعلى", isMakke: true, numberOfAyat: 19),
  SuraNameModel(name: "الغاشية", isMakke: true, numberOfAyat: 26),
  SuraNameModel(name: "الفجر", isMakke: true, numberOfAyat: 30),
  SuraNameModel(name: "البلد", isMakke: true, numberOfAyat: 20),
  SuraNameModel(name: "الشمس", isMakke: true, numberOfAyat: 15),
  SuraNameModel(name: "الليل", isMakke: true, numberOfAyat: 21),
  SuraNameModel(name: "الضحى", isMakke: true, numberOfAyat: 11),
  SuraNameModel(name: "الشرح", isMakke: true, numberOfAyat: 8),
  SuraNameModel(name: "التين", isMakke: true, numberOfAyat: 8),
  SuraNameModel(name: "العلق", isMakke: true, numberOfAyat: 19),
  SuraNameModel(name: "القدر", isMakke: true, numberOfAyat: 5),
  SuraNameModel(name: "البينة", isMakke: true, numberOfAyat: 8),
  SuraNameModel(name: "الزلزلة", isMakke: true, numberOfAyat: 8),
  SuraNameModel(name: "العاديات", isMakke: true, numberOfAyat: 11),
  SuraNameModel(name: "القارعة", isMakke: true, numberOfAyat: 11),
  SuraNameModel(name: "التكاثر", isMakke: true, numberOfAyat: 8),
  SuraNameModel(name: "العصر", isMakke: true, numberOfAyat: 3),
  SuraNameModel(name: "الهمزة", isMakke: true, numberOfAyat: 9),
  SuraNameModel(name: "الفيل", isMakke: true, numberOfAyat: 5),
  SuraNameModel(name: "قريش", isMakke: true, numberOfAyat: 4),
  SuraNameModel(name: "الماعون", isMakke: true, numberOfAyat: 7),
  SuraNameModel(name: "الكوثر", isMakke: true, numberOfAyat: 3),
  SuraNameModel(name: "الكافرون", isMakke: true, numberOfAyat: 6),
  SuraNameModel(name: "النصر", isMakke: true, numberOfAyat: 3),
  SuraNameModel(name: "المسد", isMakke: true, numberOfAyat: 5),
  SuraNameModel(name: "الإخلاص", isMakke: true, numberOfAyat: 4),
  SuraNameModel(name: "الفلق", isMakke: true, numberOfAyat: 5),
  SuraNameModel(name: "الناس", isMakke: true, numberOfAyat: 6),
];
