class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Werdy',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'quran_text': 'Quran Text',
      'font_size': 'Font Size',
      'font_family': 'Font Family',
      'reminders': 'Reminders',
      'morning_adhkar': 'Morning Adhkar',
      'evening_adhkar': 'Evening Adhkar',
      'change_time': 'Change Time',
      'scheduled_at': 'Scheduled at',
      'reset': 'Reset',
      'last_read': 'Last Read',
      'continue_reading': 'Continue',
      'quick_access': 'Quick Access',
      'prayer': 'Prayer',
      'favorites': 'Favorites',
      'morning': 'Morning',
      'evening': 'Evening',
      'search_surah': 'Search Surah...',
      'holy_quran': 'Holy Quran',
      'adhkar_title': 'Adhkar',
      'language': 'Language',
      'select_language': 'Select Language',
      'home_tab': 'Home',
      'quran_tab': 'Quran',
      'qibla_direction': 'Qibla Direction',
      'prayer_times': 'Prayer Times',
      'calibrate_compass': 'Please calibrate your compass',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'reading_goals': 'Reading Goals',
      'statistics': 'Statistics',
      'achievements': 'Achievements',
      'create_goal': 'Create Goal',
      'goal_title': 'Goal Title',
      'target': 'Target',
      'period': 'Period',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'custom': 'Custom',
      'verses': 'Verses',
      'pages': 'Pages',
      'juz': 'Juz',
      'time': 'Time',
      'minutes': 'Minutes',
      'progress': 'Progress',
      'completed': 'Completed',
      'active': 'Active',
      'total_read_time': 'Total Read Time',
      'total_verses': 'Total Verses',
      'sessions': 'Sessions',
      'streak': 'Streak',
      'days': 'Days',
    },
    'ar': {
      'app_title': 'وردي',
      'settings': 'الإعدادات',
      'appearance': 'المظهر',
      'dark_mode': 'الوضع الليلي',
      'quran_text': 'نص القرآن',
      'font_size': 'حجم الخط',
      'font_family': 'نوع الخط',
      'reminders': 'التنبيهات',
      'morning_adhkar': 'أذكار الصباح',
      'evening_adhkar': 'أذكار المساء',
      'change_time': 'تغيير الوقت',
      'scheduled_at': 'مجدول في',
      'reset': 'إعادة تعيين',
      'last_read': 'آخر قراءة',
      'continue_reading': 'تابع القراءة',
      'quick_access': 'وصول سريع',
      'prayer': 'الصلاة',
      'favorites': 'المفضلة',
      'morning': 'صباح',
      'evening': 'مساء',
      'search_surah': 'بحث عن سورة...',
      'holy_quran': 'القرآن الكريم',
      'adhkar_title': 'الأذكار',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'home_tab': 'الرئيسية',
      'quran_tab': 'المصحف',
      'qibla_direction': 'اتجاه القبلة',
      'prayer_times': 'مواقيت الصلاة',
      'calibrate_compass': 'يرجى معايرة البوصلة',
      'latitude': 'خط العرض',
      'longitude': 'خط الطول',
      'reading_goals': 'أهداف القراءة',
      'statistics': 'الإحصائيات',
      'achievements': 'الإنجازات',
      'create_goal': 'إنشاء هدف',
      'goal_title': 'عنوان الهدف',
      'target': 'الهدف',
      'period': 'الفترة',
      'daily': 'يومي',
      'weekly': 'أسبوعي',
      'monthly': 'شهري',
      'custom': 'مخصص',
      'verses': 'آيات',
      'pages': 'صفحات',
      'juz': 'أجزاء',
      'time': 'وقت',
      'minutes': 'دقائق',
      'progress': 'التقدم',
      'completed': 'مكتمل',
      'active': 'نشط',
      'total_read_time': 'وقت القراءة الكلي',
      'total_verses': 'مجموع الآيات',
      'sessions': 'الجلسات',
      'streak': 'التتابع',
      'days': 'أيام',
    },
  };

  static String get(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
