class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Werdy',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'quran_text': 'Quran Text',
      'font_size': 'Font Size',
      'font_family': 'Font Family',
      'reminders': 'Reminders',
      'morning_adhkar': 'Morning Adhkar',
      'evening_adhkar': 'Evening Adhkar',
      'change_time': 'Change Time',
      'scheduled_at': 'Scheduled at',
      'reset': 'Reset',
      'last_read': 'Last Read',
      'continue_reading': 'Continue',
      'quick_access': 'Quick Access',
      'prayer': 'Prayer',
      'favorites': 'Favorites',
      'morning': 'Morning',
      'evening': 'Evening',
      'search_surah': 'Search Surah...',
      'holy_quran': 'Holy Quran',
      'adhkar_title': 'Adhkar',
      'select_language': 'Select Language',
      'home_tab': 'Home',
      'quran_tab': 'Quran',
    },
    'ar': {
      'app_title': 'وردي',
      'settings': 'الإعدادات',
      'appearance': 'المظهر',
      'dark_mode': 'الوضع الليلي',
      'quran_text': 'نص القرآن',
      'font_size': 'حجم الخط',
      'font_family': 'نوع الخط',
      'reminders': 'التنبيهات',
      'morning_adhkar': 'أذكار الصباح',
      'evening_adhkar': 'أذكار المساء',
      'change_time': 'تغيير الوقت',
      'scheduled_at': 'مجدول في',
      'reset': 'إعادة تعيين',
      'last_read': 'آخر قراءة',
      'continue_reading': 'تابع القراءة',
      'quick_access': 'وصول سريع',
      'prayer': 'الصلاة',
      'favorites': 'المفضلة',
      'morning': 'صباح',
      'evening': 'مساء',
      'search_surah': 'بحث عن سورة...',
      'holy_quran': 'القرآن الكريم',
      'adhkar_title': 'الأذكار',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'home_tab': 'الرئيسية',
      'quran_tab': 'المصحف',
    },
  };

  static String get(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
